### ISSUE TITLE
How to configure the scan path?

### ISSUE THREAD

**Issue by davidonlaptop** [getgauge-contrib/gauge-maven-plugin#57]
Hi there, I am using gauge on a big project with lots of dependencies and the class path scanner goes crazy. 18 seconds is spent on scanning and 45ms on executing my hello world step.

I am running gauge through maven `mvn test`, and here's the end of the trace:

```
...
18:23:12.265 [main] WARN org.reflections.Reflections - could not get type for name org.springframework.session.data.mongo.config.annotation.web.http.MongoHttpSessionConfiguration from any class loader
org.reflections.ReflectionsException: could not get type for name org.springframework.session.data.mongo.config.annotation.web.http.MongoHttpSessionConfiguration
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:59)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
        at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:82)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:54)
Caused by: java.lang.ClassNotFoundException: org.springframework.session.data.mongo.config.annotation.web.http.MongoHttpSessionConfiguration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 6 common frames omitted
18:23:12.266 [main] WARN org.reflections.Reflections - could not get type for name liquibase.integration.spring.SpringLiquibase from any class loader
org.reflections.ReflectionsException: could not get type for name liquibase.integration.spring.SpringLiquibase
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:59)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
        at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:82)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:54)
Caused by: java.lang.ClassNotFoundException: liquibase.integration.spring.SpringLiquibase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 6 common frames omitted
# Specification Heading
  ## First test helllllo from sice security saml
 ✔

Successfully generated html-report to => /Users/dlauzon/workspace/ice/ice-security/ice-security-saml/reports/html-report/index.html
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      1 executed      1 passed        0 failed        0 skipped

Total time taken: 45ms
Updates are available. Run `gauge update -c` for more info.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.409 s
[INFO] Finished at: 2019-09-12T18:23:12-04:00
[INFO] ------------------------------------------------------------------------
```

All exceptions looks similar with only the `MethodAnnotationsScanner` / `SubTypesScanner` changing and the file it is trying to scan. It's even trying to scan inside the maven dependencies.

Is it possible to tell it where to scan the gauge spec / steps ?  or tell it to scan only in the current project?

**Comment by shubhamsc** [comment]
@davidonlaptop I think you're searching for this env variable `package_to_scan` to configure the scan path. It will scan only the given packages. There is some discussion around that, which may help. https://github.com/getgauge/gauge-java/issues/161

**Comment by davidonlaptop** [comment]
That is exactly what I was looking for! Thank you shubhamsc!
